#!/usr/bin/env php
<?php
foreach ([
__DIR__ . '/../../autoload.php',
 __DIR__ . '/../vendor/autoload.php',
 __DIR__ . '/vendor/autoload.php'
] as $file) {
    if (file_exists($file)) {
        define('BEVERAGE_COMPOSER_INSTALL', $file);
        break;
    }
}

unset($file);

if (!defined('BEVERAGE_COMPOSER_INSTALL')) {
    fwrite(STDERR, 'You need to set up the project dependencies using the following commands:' . PHP_EOL .
            'wget http://getcomposer.org/composer.phar' . PHP_EOL .
            'php composer.phar install' . PHP_EOL
    );
    die(1);
}

require BEVERAGE_COMPOSER_INSTALL;

use Awakenweb\Beverage\Command\Run;
use Awakenweb\Beverage\Command\Watch;
use Awakenweb\Beverage\Command\JsMinifier;
use Awakenweb\Beverage\Command\CssMinifier;
use Awakenweb\Beverage\Command\Init;
use Symfony\Component\Console\Application;

$runner      = new Run();
$application = new Application('Awakenweb Beverage', '0.1');
$application->add($runner);
$application->setDefaultCommand($runner->getName());
$application->add(new Init());
$application->run();
